version: '3.8'

services:
  app:
    build: ./my-nodejs-api
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./my-nodejs-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  react-app:
    build: ./my-react-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - app

volumes:
  db_data: