services:
  api:
    build:
      context: ./my-nodejs-api
    env_file:
      - ./my-nodejs-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  react-app:
    build:
      context: ./my-react-app
    env_file:
      - ./my-react-app/.env
    ports:
      - "3001:3000"
    depends_on:
      - api

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: