name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create .env file for Docker build
      - name: Create .env file
        run: |
          echo "SPLIT_API_KEY=${{ secrets.SPLIT_API_KEY }}" >> .env
          echo "API_URL=http://localhost:3000" >> .env
          echo "CLIENT_URL=http://localhost:3001" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env

      # Build Docker image for the API service
      - name: Build Docker image for API
        id: build_api
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }} ./my-nodejs-api
          echo "api_image=${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }}" >> $GITHUB_ENV

      # Build Docker image for the React service
      - name: Build Docker image for React App
        id: build_react
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-react-app:${{ github.sha }} ./my-react-app
          echo "react_image=${{ secrets.ACR_NAME }}.azurecr.io/my-react-app:${{ github.sha }}" >> $GITHUB_ENV

      # Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Push Docker images to ACR
      - name: Push Docker images to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-react-app:${{ github.sha }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy API to Azure Container Apps (DEV)
      - name: Deploy API to Azure Container Apps (DEV)
        run: |
          az containerapp up \
            --name my-api-dev \
            --resource-group my-resource-group \
            --image ${{ env.api_image }} \
            --target-port 3000 \
            --environment my-environment \
            --cpu 0.5 --memory 1.0Gi

      # Deploy React App to Azure Container Apps (DEV)
      - name: Deploy React App to Azure Container Apps (DEV)
        run: |
          az containerapp up \
            --name my-react-app-dev \
            --resource-group my-resource-group \
            --image ${{ env.react_image }} \
            --target-port 80 \
            --environment my-environment \
            --cpu 0.5 --memory 1.0Gi

  deploy-qa:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy API to Azure Container Apps (QA)
      - name: Deploy API to Azure Container Apps (QA)
        run: |
          az containerapp up \
            --name my-api-qa \
            --resource-group my-resource-group \
            --image ${{ env.api_image }} \
            --target-port 3000 \
            --environment my-environment \
            --cpu 0.5 --memory 1.0Gi

      # Deploy React App to Azure Container Apps (QA)
      - name: Deploy React App to Azure Container Apps (QA)
        run: |
          az containerapp up \
            --name my-react-app-qa \
            --resource-group my-resource-group \
            --image ${{ env.react_image }} \
            --target-port 80 \
            --environment my-environment \
            --cpu 0.5 --memory 1.0Gi

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-qa
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy API to Azure Container Apps (PROD)
      - name: Deploy API to Azure Container Apps (PROD)
        run: |
          az containerapp up \
            --name my-api-prod \
            --resource-group my-resource-group \
            --image ${{ env.api_image }} \
            --target-port 3000 \
            --environment my-environment \
            --cpu 1.0 --memory 2.0Gi

      # Deploy React App to Azure Container Apps (PROD)
      - name: Deploy React App to Azure Container Apps (PROD)
        run: |
          az containerapp up \
            --name my-react-app-prod \
            --resource-group my-resource-group \
            --image ${{ env.react_image }} \
            --target-port 80 \
            --environment my-environment \
            --cpu 1.0 --memory 2.0Gi